services:
  backend:
    build: . # Construindo a imagem a partir do Dockerfile na raiz do diretório
    container_name: flashcard # Nome do container
    ports:
      - "25000:25000" # Mapeando a porta 25000 do container para a porta 25000 da máquina host
    environment: # Variáveis de ambiente para configuração do banco de dados passadas via terminal
      - SPRING_DATASOURCE_URL=${DB_URL} # URL do banco de dados
      - SPRING_DATASOURCE_USERNAME=${DB_USER} # Usuário do banco de dados
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} # Senha do banco de dados